export const dummyInfo = `Greek mythology is the body of myths originally told by the ancient Greeks, and a genre of ancient Greek folklore, today absorbed alongside Roman mythology into the broader designation of classical mythology. These stories concern the ancient Greek religion's view of the origin and nature of the world; the lives and activities of deities, heroes, and mythological creatures; and the origins and significance of the ancient Greeks' cult and ritual practices. Modern scholars study the myths to shed light on the religious and political institutions of ancient Greece, and to better understand the nature of myth-making itself.[1]

The Greek myths were initially propagated in an oral-poetic tradition most likely by Minoan and Mycenaean singers starting in the 18th century BC;[2] eventually the myths of the heroes of the Trojan War and its aftermath became part of the oral tradition of Homer's epic poems, the Iliad and the Odyssey. Two poems by Homer's near contemporary Hesiod, the Theogony and the Works and Days, contain accounts of the genesis of the world, the succession of divine rulers, the succession of human ages, the origin of human woes, and the origin of sacrificial practices. Myths are also preserved in the Homeric Hymns, in fragments of epic poems of the Epic Cycle, in lyric poems, in the works of the tragedians and comedians of the fifth century BC, in writings of scholars and poets of the Hellenistic Age, and in texts from the time of the Roman Empire by writers such as Plutarch and Pausanias.

Aside from this narrative deposit in ancient Greek literature, pictorial representations of gods, heroes, and mythic episodes featured prominently in ancient vase paintings and the decoration of votive gifts and many other artifacts. Geometric designs on pottery of the eighth century BC depict scenes from the Epic Cycle as well as the adventures of Heracles. In the succeeding Archaic, Classical, and Hellenistic periods, Homeric and various other mythological scenes appear, supplementing the existing literary evidence.[3]

Greek mythology has had an extensive influence on the culture, arts, and literature of Western civilization and remains part of Western heritage and language. Poets and artists from ancient times to the present have derived inspiration from Greek mythology and have discovered contemporary significance and relevance in the themes.[4]: 43 


Achilles and Penthesileia by Exekias, c. 540 BC, British Museum, London
Sources
Greek mythology is known today primarily from Greek literature and representations on visual media dating from the Geometric period from c. 900 BC to c. 800 BC onward.[5]: 200  In fact, literary and archaeological sources integrate, sometimes mutually supportive and sometimes in conflict; however, in many cases, the existence of this corpus of data is a strong indication that many elements of Greek mythology have strong factual and historical roots.[6]

Literary sources
Mythical narration plays an important role in nearly every genre of Greek literature. Nevertheless, the only general mythographical handbook to survive from Greek antiquity was the Library of Pseudo-Apollodorus. This work attempts to reconcile the contradictory tales of the poets and provides a grand summary of traditional Greek mythology and heroic legends.[7]: 1  Apollodorus of Athens lived from c. 180 BC to c. 125 BC and wrote on many of these topics. His writings may have formed the basis for the collection; however, the "Library" discusses events that occurred long after his death, hence the name Pseudo-Apollodorus.


Prometheus (1868 by Gustave Moreau). The myth of Prometheus first was attested by Hesiod and then constituted the basis for a tragic trilogy of plays, possibly by Aeschylus, consisting of Prometheus Bound, Prometheus Unbound, and Prometheus Pyrphoros.
Among the earliest literary sources are Homer's two epic poems, the Iliad and the Odyssey. Other poets completed the Epic Cycle, but these later and lesser poems now are lost almost entirely. Despite their traditional name, the Homeric Hymns have no direct connection with Homer. The oldest are choral hymns from the earlier part of the so-called Lyric age.[8]: 7  Hesiod, a possible contemporary with Homer, offers in his Theogony (Origin of the Gods) the fullest account of the earliest Greek myths, dealing with the creation of the world, the origin of the gods, Titans, and Giants, as well as elaborate genealogies, folktales, and aetiological myths. Hesiod's Works and Days, a didactic poem about farming life, also includes the myths of Prometheus, Pandora, and the Five Ages. The poet advises on the best way to succeed in a dangerous world, rendered yet more dangerous by its gods.[3]

Lyrical poets often took their subjects from myth, but their treatment became gradually less narrative and more allusive. Greek lyric poets, including Pindar, Bacchylides and Simonides, and bucolic poets such as Theocritus and Bion, relate individual mythological incidents.[9]: xii  Additionally, myth was central to classical Athenian drama. The tragic playwrights Aeschylus, Sophocles, and Euripides took most of their plots from myths of the age of heroes and the Trojan War. Many of the great tragic stories (e.g. Agamemnon and his children, Oedipus, Jason, Medea, etc.) took on their classic form in these tragedies. The comic playwright Aristophanes also used myths, in The Birds and The Frogs.[8]: 8 

Historians Herodotus and Diodorus Siculus, and geographers Pausanias and Strabo, who traveled throughout the Greek world and noted the stories they heard, supplied numerous local myths and legends, often giving little-known alternative versions.[9]: xii  Herodotus in particular, searched the various traditions he encountered and found the historical or mythological roots in the confrontation between Greece and the East.[10]: 60 [11]: 22  Herodotus attempted to reconcile origins and the blending of differing cultural concepts.

The poetry of the Hellenistic and Roman ages was primarily composed as a literary rather than cultic exercise. Nevertheless, it contains many important details that would otherwise be lost. This category includes the works of:

The Roman poets Ovid, Statius, Valerius Flaccus, Seneca and Virgil with Servius's commentary.
The Greek poets of the Late Antique period: Nonnus, Antoninus Liberalis, and Quintus Smyrnaeus.
The Greek poets of the Hellenistic period: Apollonius of Rhodes, Callimachus, Pseudo-Eratosthenes, and Parthenius.
Prose writers from the same periods who make reference to myths include Apuleius, Petronius, Lollianus, and Heliodorus. Two other important non-poetical sources are the Fabulae and Astronomica of the Roman writer styled as Pseudo-Hyginus, the Imagines of Philostratus the Elder and Philostratus the Younger, and the Descriptions of Callistratus.

Finally, several Byzantine Greek writers provide important details of myth, much derived from earlier now lost Greek works. These preservers of myth include Arnobius, Hesychius, the author of the Suda, John Tzetzes, and Eustathius. They often treat mythology from a Christian moralizing perspective.[12]`;
