export default [
	{ value: 'russian', label: 'Russian' },
	{ value: 'french', label: 'French' },
	{ value: 'italian', label: 'Italian' },
	{ value: 'german', label: 'German' },
	{ value: 'english', label: 'English' },
	{ value: 'icelandic', label: 'Icelandic' },
	{ value: 'faroese', label: 'Faroese' },
	{ value: 'norwegian', label: 'Norwegian' },
	{ value: 'swedish', label: 'Swedish' },
	{ value: 'danish', label: 'Danish' },
	{ value: 'dutch', label: 'Dutch' },
	{ value: 'spanish', label: 'Spanish' },
	{ value: 'romanian', label: 'Romanian' },
	{ value: 'portuguese', label: 'Portuguese' },
	{ value: 'catalan', label: 'Catalan' },
	{ value: 'polish', label: 'Polish' },
	{ value: 'ukrainian', label: 'Ukrainian' },
	{ value: 'serbo-croatian', label: 'Serbo-Croatian' },
	{ value: 'czech', label: 'Czech' },
	{ value: 'bulgarian', label: 'Bulgarian' },
	{ value: 'greek', label: 'Greek' },
	{ value: 'lithuanian', label: 'Lithuanian' },
	{ value: 'latvian', label: 'Latvian' },
	{ value: 'albanian', label: 'Albanian' },
	{ value: 'armenian', label: 'Armenian' },
	{ value: 'welsh', label: 'Welsh' },
	{ value: 'irish', label: 'Irish' },
	{ value: 'scottish-gaelic', label: 'Scottish Gaelic' },
	{ value: 'romani', label: 'Romani' },
];
